# Add a needs triage for each browser to all new issues
"needs-triage: chrome":
  - ""

"needs-triage: safari": 
  - ""

"needs-triage: firefox": 
  - ""

"needs-triage%3A safari": 
  - ""

"needs-triage%3A firefox": 
  - ""
